--- luci-app-ssr-plus/Makefile
+++ luci-app-ssr-plus/Makefile
@@ -124,19 +128,15 @@ config PACKAGE_$(PKG_NAME)_INCLUDE_MosDNS
 
 config PACKAGE_$(PKG_NAME)_INCLUDE_Http_Proxy
 	bool "Include HTTP(S) Proxy Server"
-	select PACKAGE_3proxy
-	default y if (aarch64||arm||i386||loongarch64||riscv64||x86_64)
+	default y if (aarch64||i386||loongarch64||riscv64||x86_64)
 
 config PACKAGE_$(PKG_NAME)_INCLUDE_Mihomo
 	bool "Include Mihomo (Clash Support)"
-	select PACKAGE_mihomo
 	depends on aarch64||arm||i386||loongarch64||riscv64||x86_64
 	default y if aarch64||arm||i386||loongarch64||riscv64||x86_64
 
 config PACKAGE_$(PKG_NAME)_INCLUDE_GeoData
 	bool "Include GeoData (GeoIP and GeoSite)"
-	select PACKAGE_v2ray-geoip
-	select PACKAGE_v2ray-geosite
 	default y if i386||x86_64
 
 config PACKAGE_$(PKG_NAME)_INCLUDE_Shadow_TLS
